import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {
  Inter,
  Oswald,
  Raleway,
  Poppins,
  Montserrat,
  Lato,
} from "next/font/google";
import { Toaster } from "sonner";

const inter = Inter({
  variable: "--font-inter",
  weight: ["100", "200", "300", "500", "700"],
  subsets: ["greek"],
});
const raleway = Raleway({
  variable: "--font-raleway",
  weight: ["100", "200", "300", "500", "700"],
  subsets: ["cyrillic", "cyrillic-ext", "latin", "latin-ext", "vietnamese"],
});
const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["100", "200", "300", "500", "700"],
  subsets: ["latin", "latin-ext"],
});
const montserrat = Montserrat({
  variable: "--font-montserrat",
  weight: ["100", "200", "300", "500", "700"],
  subsets: ["cyrillic", "cyrillic-ext", "latin", "vietnamese"],
});
const lato = Lato({
  variable: "--font-lato",
  weight: ["100", "300", "700", "900"],
  subsets: ["latin"],
  display: "swap",
});
const oswald = Oswald({
  variable: "--font-oswald",
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
});
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${raleway.variable} ${poppins.variable} ${montserrat.variable} ${lato.variable} ${oswald.variable} ${inter.variable} ${geistMono.variable} font-raleway antialiased`}
      >
        {children}
        <Toaster
          richColors={true}
          duration={4000}
          theme="system"
          position="bottom-right"
        />
      </body>
    </html>
  );
}
